# Generated by Django 3.1.7 on 2021-03-04 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topiapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crear_Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ingrese su nombre', max_length=150)),
                ('apellido', models.CharField(help_text='Ingrese su apellido', max_length=150)),
                ('email', models.EmailField(help_text='Ingrese su E-mail', max_length=254, verbose_name='E-mail')),
                ('contraseña', models.CharField(help_text='Ingrese su contraseña', max_length=150, verbose_name='Contraseña')),
            ],
            options={
                'db_table': 'nuevo usuario',
            },
        ),
    ]
